# -----------------------------------------------------------------------------
# studio_default_nodes.py
# Milton Maguna / milton.maguna@gmail.com
# 1.0.0 - First Release / 01/23/2022
# -----------------------------------------------------------------------------

import nuke

nuke.knobDefault('Root.format', 'HD_1080')
nuke.knobDefault('Root.fps', '24')
nuke.knobDefault("Root.colorManagement", "1")
nuke.knobDefault("Root.first_frame", "1001")
nuke.knobDefault("Root.last_frame", "1100")
nuke.knobDefault('Write.channels', 'rgba')
nuke.knobDefault('Merge.bbox', 'B')
nuke.knobDefault("Erode.channels", "alpha")
nuke.knobDefault("Erode.size", "1")
nuke.knobDefault("Erode.label", "[value size]")
nuke.knobDefault("Blur.label", "Size [value size]")
nuke.knobDefault("EdgeBlur.size", "2")
nuke.knobDefault("EdgeBlur.label", "[value size]")
nuke.knobDefault("EdgeDetectWrapper.channels", "alpha")
nuke.knobDefault("Roto.output", "alpha")
nuke.knobDefault("Remove.operation", "keep")
nuke.knobDefault("Remove.channels", "rgba")
nuke.knobDefault('Constant.channels', 'rgba')
nuke.knobDefault('Constant.color', '0 0 0 1.0')
nuke.knobDefault('Invert.channels', 'alpha')
nuke.knobDefault("Read.localizationPolicy", "off")
nuke.knobDefault("Write.create_directories", "on")
nuke.knobDefault("LayerContactSheet.showLayerNames", "on")
nuke.knobDefault("Crop.Crop", "1")
nuke.knobDefault("StickyNote.note_font_size", "35")
nuke.knobDefault("StickyNote.note_font", "bold")
nuke.knobDefault("PostageStamp.tile_color", "4278190335")
nuke.knobDefault("PostageStamp.hide_input", "True")
nuke.knobDefault("PostageStamp.postage_stamp", "False")
nuke.knobDefault("Shuffle.label","[value in1]")
nuke.knobDefault('Cryptomatte.RemoveChannels','1')
nuke.knobDefault('EXPTool.mode','0')
nuke.knobDefault('Read.frame_mode','1')
nuke.knobDefault('ScanlineRender.drop_zero_alpha_samples', 'False')
nuke.knobDefault('ScanlineRender.motion_vectors_type', '0')
nuke.knobDefault('ScanlineRender.MB_channel', 'none')
nuke.knobDefault('ChannelMerge.bbox', 'B')
nuke.knobDefault('TimeClip.label', '[value first]-[value last]')
nuke.knobDefault('TimeOffset.label', '[value time_offset]')
nuke.knobDefault('Retime.filter', '0')
nuke.knobDefault('Retime.before', '4.0')
nuke.knobDefault('Retime.after', '4.0')
nuke.knobDefault('STMap.channels', 'rgba')
nuke.knobDefault('STMap.uv', 'rgba')
nuke.knobDefault('OCIODisplay.invert', 'True')